from enum import Enum

class LLMProvider(str, Enum):
    GROQ_PRIMARY = "GROQ-LLAMA3"
    OPENROUTER_FALLBACK = "OPENROUTER-MISTRAL"
    GROQ_OR_FALLBACK = "GROQ_OR_FALLBACK"
    COHERE_PRIMARY = "COHERE-COMMAND"
    GEMINI_FALLBACK = "GEMINI-FLASH"
    LOCAL_RULE = "LOCAL_RULE_BASED"
    HF_CLASSIFIER = "HF_ZERO_SHOT"
