# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pose_skeleton.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13pose_skeleton.proto\x12\x04hk07\"?\n\x08Landmark\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\x12\n\nvisibility\x18\x04 \x01(\x02\"\x84\x01\n\rSkeletonFrame\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x03\x12!\n\tlandmarks\x18\x02 \x03(\x0b\x32\x0e.hk07.Landmark\x12\x13\n\x0b\x61lert_level\x18\x03 \x01(\t\x12\x14\n\x0coverall_risk\x18\x04 \x01(\t\x12\x0f\n\x07user_id\x18\x05 \x01(\tB2\n\x1d\x63om.hk07.domain.telemetry.dtoB\x11PoseSkeletonProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pose_skeleton_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.hk07.domain.telemetry.dtoB\021PoseSkeletonProto'
  _globals['_LANDMARK']._serialized_start=29
  _globals['_LANDMARK']._serialized_end=92
  _globals['_SKELETONFRAME']._serialized_start=95
  _globals['_SKELETONFRAME']._serialized_end=227
# @@protoc_insertion_point(module_scope)
