// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pose_skeleton.proto

// Protobuf Java Version: 3.25.3
package com.hk07.domain.telemetry.dto;

public final class PoseSkeletonProto {
  private PoseSkeletonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LandmarkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hk07.Landmark)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float x = 1;</code>
     * @return The x.
     */
    float getX();

    /**
     * <code>float y = 2;</code>
     * @return The y.
     */
    float getY();

    /**
     * <code>float z = 3;</code>
     * @return The z.
     */
    float getZ();

    /**
     * <code>float visibility = 4;</code>
     * @return The visibility.
     */
    float getVisibility();
  }
  /**
   * Protobuf type {@code hk07.Landmark}
   */
  public static final class Landmark extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:hk07.Landmark)
      LandmarkOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Landmark.newBuilder() to construct.
    private Landmark(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Landmark() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Landmark();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hk07.domain.telemetry.dto.PoseSkeletonProto.internal_static_hk07_Landmark_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hk07.domain.telemetry.dto.PoseSkeletonProto.internal_static_hk07_Landmark_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.class, com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private float x_ = 0F;
    /**
     * <code>float x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_ = 0F;
    /**
     * <code>float y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public float getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private float z_ = 0F;
    /**
     * <code>float z = 3;</code>
     * @return The z.
     */
    @java.lang.Override
    public float getZ() {
      return z_;
    }

    public static final int VISIBILITY_FIELD_NUMBER = 4;
    private float visibility_ = 0F;
    /**
     * <code>float visibility = 4;</code>
     * @return The visibility.
     */
    @java.lang.Override
    public float getVisibility() {
      return visibility_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Float.floatToRawIntBits(x_) != 0) {
        output.writeFloat(1, x_);
      }
      if (java.lang.Float.floatToRawIntBits(y_) != 0) {
        output.writeFloat(2, y_);
      }
      if (java.lang.Float.floatToRawIntBits(z_) != 0) {
        output.writeFloat(3, z_);
      }
      if (java.lang.Float.floatToRawIntBits(visibility_) != 0) {
        output.writeFloat(4, visibility_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Float.floatToRawIntBits(x_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (java.lang.Float.floatToRawIntBits(y_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      if (java.lang.Float.floatToRawIntBits(z_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, z_);
      }
      if (java.lang.Float.floatToRawIntBits(visibility_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, visibility_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark)) {
        return super.equals(obj);
      }
      com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark other = (com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark) obj;

      if (java.lang.Float.floatToIntBits(getX())
          != java.lang.Float.floatToIntBits(
              other.getX())) return false;
      if (java.lang.Float.floatToIntBits(getY())
          != java.lang.Float.floatToIntBits(
              other.getY())) return false;
      if (java.lang.Float.floatToIntBits(getZ())
          != java.lang.Float.floatToIntBits(
              other.getZ())) return false;
      if (java.lang.Float.floatToIntBits(getVisibility())
          != java.lang.Float.floatToIntBits(
              other.getVisibility())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getX());
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getY());
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getZ());
      hash = (37 * hash) + VISIBILITY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getVisibility());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hk07.Landmark}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hk07.Landmark)
        com.hk07.domain.telemetry.dto.PoseSkeletonProto.LandmarkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hk07.domain.telemetry.dto.PoseSkeletonProto.internal_static_hk07_Landmark_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hk07.domain.telemetry.dto.PoseSkeletonProto.internal_static_hk07_Landmark_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.class, com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.Builder.class);
      }

      // Construct using com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        x_ = 0F;
        y_ = 0F;
        z_ = 0F;
        visibility_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hk07.domain.telemetry.dto.PoseSkeletonProto.internal_static_hk07_Landmark_descriptor;
      }

      @java.lang.Override
      public com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark getDefaultInstanceForType() {
        return com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.getDefaultInstance();
      }

      @java.lang.Override
      public com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark build() {
        com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark buildPartial() {
        com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark result = new com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.x_ = x_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.y_ = y_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.z_ = z_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.visibility_ = visibility_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark) {
          return mergeFrom((com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark other) {
        if (other == com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.getDefaultInstance()) return this;
        if (other.getX() != 0F) {
          setX(other.getX());
        }
        if (other.getY() != 0F) {
          setY(other.getY());
        }
        if (other.getZ() != 0F) {
          setZ(other.getZ());
        }
        if (other.getVisibility() != 0F) {
          setVisibility(other.getVisibility());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                x_ = input.readFloat();
                bitField0_ |= 0x00000001;
                break;
              } // case 13
              case 21: {
                y_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 29: {
                z_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              case 37: {
                visibility_ = input.readFloat();
                bitField0_ |= 0x00000008;
                break;
              } // case 37
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private float x_ ;
      /**
       * <code>float x = 1;</code>
       * @return The x.
       */
      @java.lang.Override
      public float getX() {
        return x_;
      }
      /**
       * <code>float x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(float value) {

        x_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>float x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>float y = 2;</code>
       * @return The y.
       */
      @java.lang.Override
      public float getY() {
        return y_;
      }
      /**
       * <code>float y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(float value) {

        y_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>float y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        onChanged();
        return this;
      }

      private float z_ ;
      /**
       * <code>float z = 3;</code>
       * @return The z.
       */
      @java.lang.Override
      public float getZ() {
        return z_;
      }
      /**
       * <code>float z = 3;</code>
       * @param value The z to set.
       * @return This builder for chaining.
       */
      public Builder setZ(float value) {

        z_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>float z = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0F;
        onChanged();
        return this;
      }

      private float visibility_ ;
      /**
       * <code>float visibility = 4;</code>
       * @return The visibility.
       */
      @java.lang.Override
      public float getVisibility() {
        return visibility_;
      }
      /**
       * <code>float visibility = 4;</code>
       * @param value The visibility to set.
       * @return This builder for chaining.
       */
      public Builder setVisibility(float value) {

        visibility_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>float visibility = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVisibility() {
        bitField0_ = (bitField0_ & ~0x00000008);
        visibility_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:hk07.Landmark)
    }

    // @@protoc_insertion_point(class_scope:hk07.Landmark)
    private static final com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark();
    }

    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Landmark>
        PARSER = new com.google.protobuf.AbstractParser<Landmark>() {
      @java.lang.Override
      public Landmark parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Landmark> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Landmark> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SkeletonFrameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hk07.SkeletonFrame)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 timestamp_ms = 1;</code>
     * @return The timestampMs.
     */
    long getTimestampMs();

    /**
     * <code>repeated .hk07.Landmark landmarks = 2;</code>
     */
    java.util.List<com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark> 
        getLandmarksList();
    /**
     * <code>repeated .hk07.Landmark landmarks = 2;</code>
     */
    com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark getLandmarks(int index);
    /**
     * <code>repeated .hk07.Landmark landmarks = 2;</code>
     */
    int getLandmarksCount();
    /**
     * <code>repeated .hk07.Landmark landmarks = 2;</code>
     */
    java.util.List<? extends com.hk07.domain.telemetry.dto.PoseSkeletonProto.LandmarkOrBuilder> 
        getLandmarksOrBuilderList();
    /**
     * <code>repeated .hk07.Landmark landmarks = 2;</code>
     */
    com.hk07.domain.telemetry.dto.PoseSkeletonProto.LandmarkOrBuilder getLandmarksOrBuilder(
        int index);

    /**
     * <code>string alert_level = 3;</code>
     * @return The alertLevel.
     */
    java.lang.String getAlertLevel();
    /**
     * <code>string alert_level = 3;</code>
     * @return The bytes for alertLevel.
     */
    com.google.protobuf.ByteString
        getAlertLevelBytes();

    /**
     * <code>string overall_risk = 4;</code>
     * @return The overallRisk.
     */
    java.lang.String getOverallRisk();
    /**
     * <code>string overall_risk = 4;</code>
     * @return The bytes for overallRisk.
     */
    com.google.protobuf.ByteString
        getOverallRiskBytes();

    /**
     * <code>string user_id = 5;</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <code>string user_id = 5;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();
  }
  /**
   * Protobuf type {@code hk07.SkeletonFrame}
   */
  public static final class SkeletonFrame extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:hk07.SkeletonFrame)
      SkeletonFrameOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SkeletonFrame.newBuilder() to construct.
    private SkeletonFrame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SkeletonFrame() {
      landmarks_ = java.util.Collections.emptyList();
      alertLevel_ = "";
      overallRisk_ = "";
      userId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SkeletonFrame();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hk07.domain.telemetry.dto.PoseSkeletonProto.internal_static_hk07_SkeletonFrame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hk07.domain.telemetry.dto.PoseSkeletonProto.internal_static_hk07_SkeletonFrame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame.class, com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame.Builder.class);
    }

    public static final int TIMESTAMP_MS_FIELD_NUMBER = 1;
    private long timestampMs_ = 0L;
    /**
     * <code>int64 timestamp_ms = 1;</code>
     * @return The timestampMs.
     */
    @java.lang.Override
    public long getTimestampMs() {
      return timestampMs_;
    }

    public static final int LANDMARKS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark> landmarks_;
    /**
     * <code>repeated .hk07.Landmark landmarks = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark> getLandmarksList() {
      return landmarks_;
    }
    /**
     * <code>repeated .hk07.Landmark landmarks = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.hk07.domain.telemetry.dto.PoseSkeletonProto.LandmarkOrBuilder> 
        getLandmarksOrBuilderList() {
      return landmarks_;
    }
    /**
     * <code>repeated .hk07.Landmark landmarks = 2;</code>
     */
    @java.lang.Override
    public int getLandmarksCount() {
      return landmarks_.size();
    }
    /**
     * <code>repeated .hk07.Landmark landmarks = 2;</code>
     */
    @java.lang.Override
    public com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark getLandmarks(int index) {
      return landmarks_.get(index);
    }
    /**
     * <code>repeated .hk07.Landmark landmarks = 2;</code>
     */
    @java.lang.Override
    public com.hk07.domain.telemetry.dto.PoseSkeletonProto.LandmarkOrBuilder getLandmarksOrBuilder(
        int index) {
      return landmarks_.get(index);
    }

    public static final int ALERT_LEVEL_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object alertLevel_ = "";
    /**
     * <code>string alert_level = 3;</code>
     * @return The alertLevel.
     */
    @java.lang.Override
    public java.lang.String getAlertLevel() {
      java.lang.Object ref = alertLevel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alertLevel_ = s;
        return s;
      }
    }
    /**
     * <code>string alert_level = 3;</code>
     * @return The bytes for alertLevel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAlertLevelBytes() {
      java.lang.Object ref = alertLevel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alertLevel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OVERALL_RISK_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object overallRisk_ = "";
    /**
     * <code>string overall_risk = 4;</code>
     * @return The overallRisk.
     */
    @java.lang.Override
    public java.lang.String getOverallRisk() {
      java.lang.Object ref = overallRisk_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        overallRisk_ = s;
        return s;
      }
    }
    /**
     * <code>string overall_risk = 4;</code>
     * @return The bytes for overallRisk.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOverallRiskBytes() {
      java.lang.Object ref = overallRisk_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        overallRisk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_ID_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object userId_ = "";
    /**
     * <code>string user_id = 5;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string user_id = 5;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestampMs_ != 0L) {
        output.writeInt64(1, timestampMs_);
      }
      for (int i = 0; i < landmarks_.size(); i++) {
        output.writeMessage(2, landmarks_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(alertLevel_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, alertLevel_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(overallRisk_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, overallRisk_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestampMs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestampMs_);
      }
      for (int i = 0; i < landmarks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, landmarks_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(alertLevel_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, alertLevel_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(overallRisk_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, overallRisk_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame)) {
        return super.equals(obj);
      }
      com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame other = (com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame) obj;

      if (getTimestampMs()
          != other.getTimestampMs()) return false;
      if (!getLandmarksList()
          .equals(other.getLandmarksList())) return false;
      if (!getAlertLevel()
          .equals(other.getAlertLevel())) return false;
      if (!getOverallRisk()
          .equals(other.getOverallRisk())) return false;
      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_MS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestampMs());
      if (getLandmarksCount() > 0) {
        hash = (37 * hash) + LANDMARKS_FIELD_NUMBER;
        hash = (53 * hash) + getLandmarksList().hashCode();
      }
      hash = (37 * hash) + ALERT_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getAlertLevel().hashCode();
      hash = (37 * hash) + OVERALL_RISK_FIELD_NUMBER;
      hash = (53 * hash) + getOverallRisk().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hk07.SkeletonFrame}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hk07.SkeletonFrame)
        com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hk07.domain.telemetry.dto.PoseSkeletonProto.internal_static_hk07_SkeletonFrame_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hk07.domain.telemetry.dto.PoseSkeletonProto.internal_static_hk07_SkeletonFrame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame.class, com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame.Builder.class);
      }

      // Construct using com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestampMs_ = 0L;
        if (landmarksBuilder_ == null) {
          landmarks_ = java.util.Collections.emptyList();
        } else {
          landmarks_ = null;
          landmarksBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        alertLevel_ = "";
        overallRisk_ = "";
        userId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hk07.domain.telemetry.dto.PoseSkeletonProto.internal_static_hk07_SkeletonFrame_descriptor;
      }

      @java.lang.Override
      public com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame getDefaultInstanceForType() {
        return com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame.getDefaultInstance();
      }

      @java.lang.Override
      public com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame build() {
        com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame buildPartial() {
        com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame result = new com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame result) {
        if (landmarksBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            landmarks_ = java.util.Collections.unmodifiableList(landmarks_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.landmarks_ = landmarks_;
        } else {
          result.landmarks_ = landmarksBuilder_.build();
        }
      }

      private void buildPartial0(com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestampMs_ = timestampMs_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.alertLevel_ = alertLevel_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.overallRisk_ = overallRisk_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.userId_ = userId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame) {
          return mergeFrom((com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame other) {
        if (other == com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame.getDefaultInstance()) return this;
        if (other.getTimestampMs() != 0L) {
          setTimestampMs(other.getTimestampMs());
        }
        if (landmarksBuilder_ == null) {
          if (!other.landmarks_.isEmpty()) {
            if (landmarks_.isEmpty()) {
              landmarks_ = other.landmarks_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureLandmarksIsMutable();
              landmarks_.addAll(other.landmarks_);
            }
            onChanged();
          }
        } else {
          if (!other.landmarks_.isEmpty()) {
            if (landmarksBuilder_.isEmpty()) {
              landmarksBuilder_.dispose();
              landmarksBuilder_ = null;
              landmarks_ = other.landmarks_;
              bitField0_ = (bitField0_ & ~0x00000002);
              landmarksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLandmarksFieldBuilder() : null;
            } else {
              landmarksBuilder_.addAllMessages(other.landmarks_);
            }
          }
        }
        if (!other.getAlertLevel().isEmpty()) {
          alertLevel_ = other.alertLevel_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getOverallRisk().isEmpty()) {
          overallRisk_ = other.overallRisk_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                timestampMs_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark m =
                    input.readMessage(
                        com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.parser(),
                        extensionRegistry);
                if (landmarksBuilder_ == null) {
                  ensureLandmarksIsMutable();
                  landmarks_.add(m);
                } else {
                  landmarksBuilder_.addMessage(m);
                }
                break;
              } // case 18
              case 26: {
                alertLevel_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                overallRisk_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                userId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long timestampMs_ ;
      /**
       * <code>int64 timestamp_ms = 1;</code>
       * @return The timestampMs.
       */
      @java.lang.Override
      public long getTimestampMs() {
        return timestampMs_;
      }
      /**
       * <code>int64 timestamp_ms = 1;</code>
       * @param value The timestampMs to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampMs(long value) {

        timestampMs_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp_ms = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestampMs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestampMs_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark> landmarks_ =
        java.util.Collections.emptyList();
      private void ensureLandmarksIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          landmarks_ = new java.util.ArrayList<com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark>(landmarks_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark, com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.Builder, com.hk07.domain.telemetry.dto.PoseSkeletonProto.LandmarkOrBuilder> landmarksBuilder_;

      /**
       * <code>repeated .hk07.Landmark landmarks = 2;</code>
       */
      public java.util.List<com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark> getLandmarksList() {
        if (landmarksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(landmarks_);
        } else {
          return landmarksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .hk07.Landmark landmarks = 2;</code>
       */
      public int getLandmarksCount() {
        if (landmarksBuilder_ == null) {
          return landmarks_.size();
        } else {
          return landmarksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .hk07.Landmark landmarks = 2;</code>
       */
      public com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark getLandmarks(int index) {
        if (landmarksBuilder_ == null) {
          return landmarks_.get(index);
        } else {
          return landmarksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .hk07.Landmark landmarks = 2;</code>
       */
      public Builder setLandmarks(
          int index, com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark value) {
        if (landmarksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLandmarksIsMutable();
          landmarks_.set(index, value);
          onChanged();
        } else {
          landmarksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .hk07.Landmark landmarks = 2;</code>
       */
      public Builder setLandmarks(
          int index, com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.Builder builderForValue) {
        if (landmarksBuilder_ == null) {
          ensureLandmarksIsMutable();
          landmarks_.set(index, builderForValue.build());
          onChanged();
        } else {
          landmarksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hk07.Landmark landmarks = 2;</code>
       */
      public Builder addLandmarks(com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark value) {
        if (landmarksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLandmarksIsMutable();
          landmarks_.add(value);
          onChanged();
        } else {
          landmarksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .hk07.Landmark landmarks = 2;</code>
       */
      public Builder addLandmarks(
          int index, com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark value) {
        if (landmarksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLandmarksIsMutable();
          landmarks_.add(index, value);
          onChanged();
        } else {
          landmarksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .hk07.Landmark landmarks = 2;</code>
       */
      public Builder addLandmarks(
          com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.Builder builderForValue) {
        if (landmarksBuilder_ == null) {
          ensureLandmarksIsMutable();
          landmarks_.add(builderForValue.build());
          onChanged();
        } else {
          landmarksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hk07.Landmark landmarks = 2;</code>
       */
      public Builder addLandmarks(
          int index, com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.Builder builderForValue) {
        if (landmarksBuilder_ == null) {
          ensureLandmarksIsMutable();
          landmarks_.add(index, builderForValue.build());
          onChanged();
        } else {
          landmarksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hk07.Landmark landmarks = 2;</code>
       */
      public Builder addAllLandmarks(
          java.lang.Iterable<? extends com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark> values) {
        if (landmarksBuilder_ == null) {
          ensureLandmarksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, landmarks_);
          onChanged();
        } else {
          landmarksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .hk07.Landmark landmarks = 2;</code>
       */
      public Builder clearLandmarks() {
        if (landmarksBuilder_ == null) {
          landmarks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          landmarksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .hk07.Landmark landmarks = 2;</code>
       */
      public Builder removeLandmarks(int index) {
        if (landmarksBuilder_ == null) {
          ensureLandmarksIsMutable();
          landmarks_.remove(index);
          onChanged();
        } else {
          landmarksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .hk07.Landmark landmarks = 2;</code>
       */
      public com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.Builder getLandmarksBuilder(
          int index) {
        return getLandmarksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .hk07.Landmark landmarks = 2;</code>
       */
      public com.hk07.domain.telemetry.dto.PoseSkeletonProto.LandmarkOrBuilder getLandmarksOrBuilder(
          int index) {
        if (landmarksBuilder_ == null) {
          return landmarks_.get(index);  } else {
          return landmarksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .hk07.Landmark landmarks = 2;</code>
       */
      public java.util.List<? extends com.hk07.domain.telemetry.dto.PoseSkeletonProto.LandmarkOrBuilder> 
           getLandmarksOrBuilderList() {
        if (landmarksBuilder_ != null) {
          return landmarksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(landmarks_);
        }
      }
      /**
       * <code>repeated .hk07.Landmark landmarks = 2;</code>
       */
      public com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.Builder addLandmarksBuilder() {
        return getLandmarksFieldBuilder().addBuilder(
            com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.getDefaultInstance());
      }
      /**
       * <code>repeated .hk07.Landmark landmarks = 2;</code>
       */
      public com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.Builder addLandmarksBuilder(
          int index) {
        return getLandmarksFieldBuilder().addBuilder(
            index, com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.getDefaultInstance());
      }
      /**
       * <code>repeated .hk07.Landmark landmarks = 2;</code>
       */
      public java.util.List<com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.Builder> 
           getLandmarksBuilderList() {
        return getLandmarksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark, com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.Builder, com.hk07.domain.telemetry.dto.PoseSkeletonProto.LandmarkOrBuilder> 
          getLandmarksFieldBuilder() {
        if (landmarksBuilder_ == null) {
          landmarksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark, com.hk07.domain.telemetry.dto.PoseSkeletonProto.Landmark.Builder, com.hk07.domain.telemetry.dto.PoseSkeletonProto.LandmarkOrBuilder>(
                  landmarks_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          landmarks_ = null;
        }
        return landmarksBuilder_;
      }

      private java.lang.Object alertLevel_ = "";
      /**
       * <code>string alert_level = 3;</code>
       * @return The alertLevel.
       */
      public java.lang.String getAlertLevel() {
        java.lang.Object ref = alertLevel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          alertLevel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string alert_level = 3;</code>
       * @return The bytes for alertLevel.
       */
      public com.google.protobuf.ByteString
          getAlertLevelBytes() {
        java.lang.Object ref = alertLevel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          alertLevel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string alert_level = 3;</code>
       * @param value The alertLevel to set.
       * @return This builder for chaining.
       */
      public Builder setAlertLevel(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        alertLevel_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string alert_level = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlertLevel() {
        alertLevel_ = getDefaultInstance().getAlertLevel();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string alert_level = 3;</code>
       * @param value The bytes for alertLevel to set.
       * @return This builder for chaining.
       */
      public Builder setAlertLevelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        alertLevel_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object overallRisk_ = "";
      /**
       * <code>string overall_risk = 4;</code>
       * @return The overallRisk.
       */
      public java.lang.String getOverallRisk() {
        java.lang.Object ref = overallRisk_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          overallRisk_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string overall_risk = 4;</code>
       * @return The bytes for overallRisk.
       */
      public com.google.protobuf.ByteString
          getOverallRiskBytes() {
        java.lang.Object ref = overallRisk_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          overallRisk_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string overall_risk = 4;</code>
       * @param value The overallRisk to set.
       * @return This builder for chaining.
       */
      public Builder setOverallRisk(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        overallRisk_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string overall_risk = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearOverallRisk() {
        overallRisk_ = getDefaultInstance().getOverallRisk();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string overall_risk = 4;</code>
       * @param value The bytes for overallRisk to set.
       * @return This builder for chaining.
       */
      public Builder setOverallRiskBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        overallRisk_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string user_id = 5;</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_id = 5;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_id = 5;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        userId_ = getDefaultInstance().getUserId();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 5;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:hk07.SkeletonFrame)
    }

    // @@protoc_insertion_point(class_scope:hk07.SkeletonFrame)
    private static final com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame();
    }

    public static com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SkeletonFrame>
        PARSER = new com.google.protobuf.AbstractParser<SkeletonFrame>() {
      @java.lang.Override
      public SkeletonFrame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SkeletonFrame> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SkeletonFrame> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hk07.domain.telemetry.dto.PoseSkeletonProto.SkeletonFrame getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hk07_Landmark_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hk07_Landmark_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hk07_SkeletonFrame_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hk07_SkeletonFrame_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023pose_skeleton.proto\022\004hk07\"?\n\010Landmark\022" +
      "\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\022\022\n\nvisi" +
      "bility\030\004 \001(\002\"\204\001\n\rSkeletonFrame\022\024\n\014timest" +
      "amp_ms\030\001 \001(\003\022!\n\tlandmarks\030\002 \003(\0132\016.hk07.L" +
      "andmark\022\023\n\013alert_level\030\003 \001(\t\022\024\n\014overall_" +
      "risk\030\004 \001(\t\022\017\n\007user_id\030\005 \001(\tB2\n\035com.hk07." +
      "domain.telemetry.dtoB\021PoseSkeletonProtob" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_hk07_Landmark_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hk07_Landmark_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hk07_Landmark_descriptor,
        new java.lang.String[] { "X", "Y", "Z", "Visibility", });
    internal_static_hk07_SkeletonFrame_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hk07_SkeletonFrame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hk07_SkeletonFrame_descriptor,
        new java.lang.String[] { "TimestampMs", "Landmarks", "AlertLevel", "OverallRisk", "UserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
